### ISSUE TITLE
Load existing LetsEncrypt Cert from volume

### ISSUE THREAD

**Issue by mricharz** [NginxProxyManager/nginx-proxy-manager#2347]
### My problem
I have the problem, that my OPNSense Firewall is already challenging ACME Wildcard Certificate. OPNSense has the ability to transfer the certificates to remote machines with automation. So far, so fine.

With NPM i only have the possibility to upload single certificate files and i need to reupload them over and over again if a new cert from ACME was requested.
I cannot load an existing `/etc/letsencrypt` folder into NPM. NPM is just ignoring its content and is not giving me an option to use the existing certificate.

### My wish
I would like that NPM is recognizing an existing certificate in `/etc/letsencrypt` and is allowing me use it.

best regards

**Comment by Jorval** [comment]
Hey,

i have a similiar problem. i update my certs on a central host where my webservices are hosted (not using npm atm)
but i like to use npm in my homelab that is behind a firewall at LE has no way to reach the host.
i would prefer an additional option that would allow me to import my already issued certificate (or let me give it a path where to find the cert)
that way i could easily ansible the certs around.

best regards.

**Comment by kaysersoze** [comment]
I would also love to have this feature, where NPM would be able to list existing certificates within a directory or mounted Docker volume.

I'm hosting my own internal CA for generating SSL certs (step-ca) and would handle the issuing and renewing of SSL certs using something like acme.sh on another container, and dropping the generated certificates in the volume for NPM to use.

**Comment by ozumado** [comment]
Hi, would love a feature like that.
I'm running two instances of NPM - local and on vps. Local one is requesting wildcard SSL certificate and I'm currently manually downloading and adding that certificate to public VPS. I would love to sync them somehow, or maybe bridge certificates from one NPM to another NPM.

**Comment by stanthewizzard** [comment]
Same

**Comment by aweb3r** [comment]
Same same

**Comment by d4nowar** [comment]
Tried to do this today, still a feature worth adding.

**Comment by lordraiden** [comment]
Is this still an issue? is there any work around so NPM can consume certs delivered via a folder path?
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2781

**Comment by BrandonMFong** [comment]
Experiencing this today trying to launch this in TrueNAS Scale:
```
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 509, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 556, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1367, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 203, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 248, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 233, in create_internal
    update_app_config(app_name, version, new_values)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/lifecycle.py", line 59, in update_app_config
    render_compose_templates(
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/lifecycle.py", line 50, in render_compose_templates
    raise CallError(f'Failed to render compose templates: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed to render compose templates: Traceback (most recent call last):
  File "/usr/bin/apps_render_app", line 33, in <module>
    sys.exit(load_entry_point('apps-validation==0.1', 'console_scripts', 'apps_render_app')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 47, in main
    render_templates_from_path(args.path, args.values)
  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 19, in render_templates_from_path
    rendered_data = render_templates(
                    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catalog_templating/render.py", line 36, in render_templates
    ).render({'ix_lib': template_libs, 'values': test_values})
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/.ix-apps/app_configs/nginx-proxy-manager/versions/1.1.9/templates/docker-compose.yaml", line 25, in top-level template code
    {% do c1.add_storage(store.mount_path, store) %}
  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/app_configs/nginx-proxy-manager/versions/1.1.9/templates/library/base_v2_1_14/container.py", line 273, in add_storage
    self._storage.add(mount_path, config)
  File "/mnt/.ix-apps/app_configs/nginx-proxy-manager/versions/1.1.9/templates/library/base_v2_1_14/storage.py", line 89, in add
    raise RenderError(f"Mount path [{mount_path}] already used for another volume mount")
base_v2_1_14.error.RenderError: Mount path [/etc/letsencrypt] already used for another volume mount
```

**Comment by joostthehost** [comment]
Also interested, so lets keep this open.

**Comment by joostthehost** [comment]
👍
