### ISSUE TITLE
Internal Error while applying let'sencrypte certificate

### ISSUE THREAD

**Issue by NankoBhai** [NginxProxyManager/nginx-proxy-manager#2860]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
 added new new proxy hosts on SSL tab applying new let's encrypte certificate and saving it gives "Internal Error"

**Nginx Proxy Manager Version**
v2.10.2

**To Reproduce**
1. Go to 'SSL'
2. Click on 'SSL certificate select request a new SSL certifcate. select force SSL, and press Save button'
4. See error - "Internal Error"

**Expected behavior**
 shall save & close the pop up

**Screenshots**

**Operating System**
 Linux server 22.04

**Additional context**

**Comment by simpixo** [comment]
have the same issue. i cant request or renew any certificates

**Comment by MurphyDoe0815** [comment]
me too. there is always an internal error.

**Comment by ajy2** [comment]
me either..

**Comment by robertklep** [comment]
Same issue here (although I'm running 2.9.22 because 2.10 never worked for me).

This is being logged:
```
[4/27/2023] [11:43:58 AM] [Express  ] › ⚠  warning   Command failed: certbot renew --config "/etc/letsencrypt.ini" --cert-name "npm-6" --disable-hook-validation --no-random-sleep-on-renew 
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 21, in <module>
    import josepy as jose
  File "/opt/certbot/lib/python3.7/site-packages/josepy/__init__.py", line 40, in <module>
    from josepy.json_util import (
  File "/opt/certbot/lib/python3.7/site-packages/josepy/json_util.py", line 14, in <module>
    from OpenSSL import crypto
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

**Comment by robertklep** [comment]
Managed to work around the issue by updating `pyopenssl` inside the container.

**Comment by simpixo** [comment]
> Managed to work around the issue by updating `pyopenssl` inside the container.

Did not fix my problem! There was installed the newest version of this package! Seems to be something other wrong in this release 😕

**Comment by robertklep** [comment]
@simpixo what's being logged?

**Comment by simpixo** [comment]
If I request a new certificate I get the following error message!

`Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-9" --agree-tos --authenticator webroot --email "Name@domain.pro" --preferred-challenges "dns,http" --domains "sub.domain.pro" 
Saving debug log to /tmp/letsencrypt-log/letsencrypt.log
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details.

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) `

a few months ago everything works fine, and nothing changed since, only the container was updated

**Comment by robertklep** [comment]
@simpixo that's a different issue from mine, so yeah, my "solution" won't fix that.

I did get the same error once while I was running a manual renew on all my certificates, specifically one for a domain that's hosted by CloudFlare (using a DNS challenge). However, after running the renew a second time it worked just fine 🤷🏼‍♂️

**Comment by Bluebird-Software** [comment]
I am getting a similar error:

```
Error: Command failed: . /opt/certbot/bin/activate && pip install --no-cache-dir --user certbot-dns-cloudflare==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') cloudflare && deactivate
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

This error comes when i visit the SSL tab.
On the Hosts tab (add or edit a host), i can also setup the SSL certificate but when selecting DNS Challenge, i only get the Internal Error without any error message

**Comment by tombauer** [comment]
I had the same problem. For me it helped to follow the instructions of AnID-Aux at https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2485. As described by AnID-Aux:

1. see what the container is called: docker ps
2. join the Container: docker exec -it CONTAINERNAME /bin/bash
3. then run the following:
4. apt update && apt dist-upgrade
5. apt install python3 python3-venv libaugeas0
6. python3 -m venv /opt/certbot/
7. pip3 install --upgrade pip
8. pip3 install certbot==1.32.0 certbot-apache==1.32.0 acme==1.32.0
9. then exit the container: exit

renewing the cert in the web interface was successful

Note: I had an error today when I had to do this again after updating the nginx proxy manager when running pip3 install --upgrade pip . Today I still had to run the command python -m pip install --upgrade pip as a priority. After that everything worked as desired :-).

Hope this helps.

**Comment by Bluebird-Software** [comment]
Tried it but got stuck at installing certbot:

`Collecting python-augeas (from certbot-apache==1.32.0)
  Using cached python-augeas-1.1.0.tar.gz (93 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [142 lines of output]
      c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
       #include <ffi.h>
                ^~~~~~~
      compilation terminated.
      Traceback (most recent call last):
        File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
          extra_postargs)
        File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
          _spawn_posix(cmd, search_path, dry_run=dry_run)
        File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
          % (cmd, exit_status))
      distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
          cmd = self.call_command('install_lib', warn_dir=0)
        File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
          self.run_command(cmdname)
        File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
          self.build()
        File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
          self.run_command('build_ext')
        File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
          _build_ext.run(self)
        File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
          _build_ext.build_extension(self, ext)
        File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
          depends=ext.depends)
        File "/usr/lib/python3.7/distutils/ccompiler.py", line 574, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-_toxup94/cffi-1.15.1/setup.py", line 242, in <module>
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.7/distutils/core.py", line 163, in setup
          raise SystemExit("error: " + str(msg))
      SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
          run_setup(setup_script, args)
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
          raise
        File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
          self.gen.throw(type, value, traceback)
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
          self.gen.throw(type, value, traceback)
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
          saved_exc.resume()
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
          six.reraise(type, exc, self._tb)
        File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-_toxup94/cffi-1.15.1/setup.py", line 242, in <module>
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.7/distutils/core.py", line 163, in setup
          raise SystemExit("error: " + str(msg))
      SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-h5e9lltc/python-augeas_236fe3eda1fc4bc589eec8625bc9c22e/setup.py", line 43, in <module>
          test_suite="test.test_augeas",
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 724, in fetch_build_eggs
          replace_conflicting=True,
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
          replace_conflicting=replace_conflicting
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
          return installer(requirement)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 791, in fetch_build_egg
          return cmd.easy_install(req)
        File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1171, in run_setup
          raise DistutilsError("Setup script exited with %s" % (v.args[0],))
      distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by AlexKusnezov** [comment]
@tombauer thank you so much. it worked oike a charm. I was able to execute everything from portainer.
Actually, the auto renewal never worked for me in nginx-proxy-manager. I always had either to request an entire new certificate manually, sometimes got an internal error. Upon this I had to do some weird stuff, like you described to get ot to work again. What can I say...

**Comment by Bluebird-Software** [comment]
For me it didn't work. I could fix my issue with installing libffi:
`apt install libffi-dev`

But i still get the same error:
```
Error: Command failed: . /opt/certbot/bin/activate && pip install --no-cache-dir --user certbot-dns-cloudflare==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') cloudflare && deactivate
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

Just for clarification, I have created a container in Proxmox (named nginx). I run those commands INSIDE the nginx container right?

I also see some websites who say i need to edit pyvenv.cfg:
include-system-site-packages from false to true, but I have no idea where i can find this file

**Comment by Chortan** [comment]
Same problem with OVH DNS Challenge.
