### ISSUE TITLE
Certbot won't start on v2.10.3

### ISSUE THREAD

**Issue by EmileSpa** [NginxProxyManager/nginx-proxy-manager#2912]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I installed 2.10.3 and immediately at startup (which takea a while) I see an error:

Error: command failed: certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --preferred-challenges "dns,http" --disable-hook-validation
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 21, in <module>
    import josepy as jose
  File "/opt/certbot/lib/python3.7/site-packages/josepy/__init__.py", line 40, in <module>
    from josepy.json_util import (
  File "/opt/certbot/lib/python3.7/site-packages/josepy/json_util.py", line 14, in <module>
    from OpenSSL import crypto
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK

When trying to issue a new certificate the same error is appearing. 

**Nginx Proxy Manager Version**
v2.10.3

**To Reproduce**
- Start the container
- Show the log with docker compose logs - f
- Wait for a while... 
- Wait for a longer time... 
- See the certbot error appear 

- Login in NPM
- Go to SSL
- Issue a new certificate
- This is failing with the same error

**Expected behavior**
Cerbot will run and try to renew certificates if necesary and is able to issue new certificates

**System**
Raspberry Pi 3 Model B Rev 1.2
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
Debian 11 with docker compose v2.17.3

**Additional context**
Docker version 23.0.5
Docker compose version 2.17.3

**Comment by EmileSpa** [comment]
Investigated this a bit further and found out the issue is caused because the python module pyOpenssl in the virtual environment /opt/certbot is outdated. It can be solved by running /opt/certbot/bin/pip3 install pyopenssl --upgrade in the container. Of coarse this is undone when the container is rebuild, so this is only a temporary solution. It should be corrected in the Dockerfile of the certbot package I suppose.

**Comment by dcazman** [comment]
I tried /opt/certbot/bin/pip3 install pyopenssl --upgrade and got error

Error: Command failed: . /opt/certbot/bin/activate && pip install --no-cache-dir --user certbot-dns-route53==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+')  && deactivate
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /opt/certbot/lib/python3.7/site-packages

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

**Comment by EmileSpa** [comment]
It looks strange that the error is showing another command then the input. Did you enter the command in the container, with docker exec - it <containername> bash?

It's a pity it doesn't work for you. Hope you'll find a working solution.

**Comment by ckoeber83** [comment]
I got Internal error if trying to renew cert on v2.10.3.

![grafik](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/52466072/e44bf503-f5d6-4fc6-ba44-5d8631f94b71)

letsencrypt.log shows me 

```
[root@docker-nginx-proxy-manager:/app]# tail -f /tmp/letsencrypt-log/letsencrypt.log
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1636, in renew
    renewal.handle_renewal_request(config)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/renewal.py", line 560, in handle_renewal_request
    f"{len(renew_failures)} renew failure(s), {len(parse_failures)} parse failure(s)")
certbot.errors.Error: 1 renew failure(s), 0 parse failure(s)
2023-05-14 20:16:19,056:ERROR:certbot._internal.log:1 renew failure(s), 0 parse failure(s)
```

**Comment by maevebaksa** [comment]
+1

**Comment by dcazman** [comment]
looks like it is also reported 
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2921

**Comment by smachi** [comment]
+1

**Comment by kikinsama** [comment]
> 

I have the same issue and apparently the problem is the `--user` parameter. A light search shows that one should not use this parameter while running on a virtual environment.

I tried running the command manually without the parameter, but got the following error:

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/29970002/779d6482-bf1b-4e0f-9902-3bf3df1905b8)
