### ISSUE TITLE
IPV6 LetsEncryp

### ISSUE THREAD

**Issue by boyi01** [NginxProxyManager/nginx-proxy-manager#3076]
**Describe the bug**
When i try to get my certificate, lets encrypt can't complete the challenge, when i open the url i can see the standart landing page of npm, so my aaaa dns should be working:

```
2023-07-24 16:08:35,862:DEBUG:acme.client:Storing nonce: 15C9rNUqj6LMPBHqg2UA0XHdZkwyeADYjnrfgJBnmygcTWA
2023-07-24 16:08:35,863:INFO:certbot._internal.auth_handler:Challenge failed for domain nasboyi.my.to
2023-07-24 16:08:35,863:INFO:certbot._internal.auth_handler:http-01 challenge for nasboyi.my.to
2023-07-24 16:08:35,863:DEBUG:certbot._internal.display.obj:Notifying user:
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: nasboyi.my.to
  Type:   connection
  Detail: 2a02:8071:52d0:dbc0:21e:6ff:fe45:25a6: Fetching http://nasboyi.my.to/.well-known/acme-challenge/l8p3qDW7pzjty7Vq16YigG7XHgIbJytAOHBrOtR-lFI: Timeout during connect (likely firewall problem)

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2023-07-24 16:08:35,866:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 90, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 178, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2023-07-24 16:08:35,866:DEBUG:certbot._internal.error_handler:Calling registered functions
2023-07-24 16:08:35,867:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-07-24 16:08:35,867:DEBUG:certbot._internal.plugins.webroot:Removing /data/letsencrypt-acme-challenge/.well-known/acme-challenge/l8p3qDW7pzjty7Vq16YigG7XHgIbJytAOHBrOtR-lFI
2023-07-24 16:08:35,867:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2023-07-24 16:08:35,868:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/certbot/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1574, in main
    return config.func(config, plugins)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1434, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 133, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 454, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 384, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 434, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 90, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 178, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2023-07-24 16:08:35,871:ERROR:certbot._internal.log:Some challenges have failed.
```

**2.9.11**

**To Reproduce**
i have enabled ipv6 like here:
https://docs.docker.com/config/daemon/ipv6/
and startet the server with this docker-compose:
```
U nano 7.2                                                                                                                   docker-compose.yml
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./ng/data:/data
      - ./ng/letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  network1:
    name: ip6net
    external: true
```

Then i create a prox host with ssl and i got the error

**Operating System**
Debian

**Comment by boyi01** [comment]
The Problem was my ipv6 config..
check if ping6 works... do not trust on a successfull call the landing page.
