### ISSUE TITLE
GoDaddy DNS Challenge: ImportError: cannot import name 'ClientBase' from 'acme.client' 

### ISSUE THREAD

**Issue by alexsalex** [NginxProxyManager/nginx-proxy-manager#3111]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

```
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-12" --agree-tos --email "piu@piu.com" --domains "*.piu.red,piu.red" --authenticator dns-godaddy --dns-godaddy-credentials "/etc/letsencrypt/credentials/credentials-12" --dns-godaddy-propagation-seconds 120
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in 
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in 
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 28, in 
    from certbot import crypto_util
  File "/opt/certbot/lib/python3.7/site-packages/certbot/crypto_util.py", line 42, in 
    from certbot import interfaces
  File "/opt/certbot/lib/python3.7/site-packages/certbot/interfaces.py", line 21, in 
    from acme.client import ClientBase
ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.7/site-packages/acme/client.py)

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket. (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe. (node:net:301:12)
```

**Nginx Proxy Manager Version**

2.10.4

**Comment by alexsalex** [comment]
Took it from here:
https://community.letsencrypt.org/t/problem-when-adding-a-certificate-on-nginx/194596


Yes, the issue is that Certbot was installed using global pip on this server. Installing Python packages globally like this is very brittle and we strongly recommend that you don't do it.

Alternative installation methods are:

[The Certbot snap 18](https://certbot.eff.org/instructions?ws=other&os=snap)
[Installing using pip via a virtual environment 19](https://certbot.eff.org/instructions?ws=other&os=pip)
More precisely, the versions of these Python modules need to be in sync:

acme
certbot
certbot-nginx

**Comment by alexsalex** [comment]
Fixed with updated **certbot-dns-godaddy**
Login to the docker container and run:
`pip install --upgrade certbot certbot-dns-godaddy`

**Comment by NetRat88** [comment]
This workaround unfortunately doesn't fix the problem :-(

**Comment by alexsalex** [comment]
Try this:
`pip install --upgrade certbot==2.1.0 certbot-dns-godaddy`
works for me.
