### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by maartenzuidland** [NginxProxyManager/nginx-proxy-manager#3122]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
[8/13/2023] [5:55:12 PM] [SSL      ] › ℹ  info      Renewing Let'sEncrypt certificates via TransIP for Cert #4: *.<domain.nl>
[8/13/2023] [5:55:12 PM] [SSL      ] › ℹ  info      Command: certbot renew --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-4" --disable-hook-validation --no-random-sleep-on-renew 
[8/13/2023] [5:55:12 PM] [Express  ] › ⚠  warning   Command failed: certbot renew --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-4" --disable-hook-validation --no-random-sleep-on-renew 
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 21, in <module>
    import josepy as jose
  File "/opt/certbot/lib/python3.7/site-packages/josepy/__init__.py", line 40, in <module>
    from josepy.json_util import (
  File "/opt/certbot/lib/python3.7/site-packages/josepy/json_util.py", line 14, in <module>
    from OpenSSL import crypto
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

**Nginx Proxy Manager Version**

v2.10.4

**To Reproduce**
1. Try renewing the *.<domain.nl> certificate
2. Get "Internal Error" 
3. Open logfiles and see this python error produced.
4. I did try debugging and reinstalling various python libraries, but this got me further from home, I pulled the latest image again, and it reverted back to the error above.

**Expected behavior**
Getting a renewed certificate.

**Operating System**
Docker / Fedora 38

**Additional context**
I tried to re-install pyopenssl as described in a previous issue, which has fixed the issue in the past, but this time it does not seem to be fixable by that (It uses the latest pyopenssl already).

**Comment by robertklep** [comment]
@maartenzuidland check out [this comment](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2881#issuecomment-1676402836)
