### ISSUE TITLE
Using aliyunDns to verify the domain name to apply for an ssl certificate failed

### ISSUE THREAD

**Issue by sanduo-656** [NginxProxyManager/nginx-proxy-manager#3142]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
   - Yes
-Are you sure you're not using someone else's docker image?
   - Yes
- Have you searched for similar issues (both open and closed)?
   - Yes

**Describe the bug**

When applying for an SSL certificate using Alibaba Cloud dns verification, the system reports an error saying socket.timeout: The read operation timed out. I have confirmed that my network is normal. I tried installing this file manually via pip, the problem persists.The following is the detailed error message:

[8/18/2023] [9:20:46 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[8/18/2023] [9:20:46 AM] [Express  ] › ⚠  warning   Command failed: . /opt/certbot/bin/activate && pip install --no-cache-dir --user certbot-dns-aliyun~=0.38.1  && deactivate
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/certbot/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/opt/certbot/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/opt/certbot/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/lib/python3.7/http/client.py", line 461, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/certbot/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/certbot/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/opt/certbot/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 378, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/opt/certbot/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=limit_how_complex_resolution_can_be
  
  File "/opt/certbot/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/certbot/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

**Nginx Proxy Manager Version**

Both 2.10.3 and 2.10.4 have this problem

**Screenshots**

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/40496018/8ffd0149-a8e6-4191-b9d5-48edda640be8)

**Operating System**

CentOS 7.9
docker version 23.0.4

**Additional context**

**Comment by qwe77889** [comment]
I also used Alibaba domain name DNS resolution and encountered the same error It hasn't been resolved yet

**Comment by ykrank** [comment]
Pip default timeout time is 15s, this is too short for some network.
