### ISSUE TITLE
Unable to renew certificate

### ISSUE THREAD

**Issue by tacyuuhon** [NginxProxyManager/nginx-proxy-manager#3164]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I renewed the certificate in the menu, but it went wrong.
```bash
# cat /tmp/certbot-log-6lhtc7_s/log 
2023-08-29 03:45:28,608:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1835, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/plugins/disco.py", line 192, in find_all
    cls._load_entry_point(entry_point, plugins)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/plugins/disco.py", line 199, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/plugins/disco.py", line 40, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/opt/certbot/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2518, in load
    return self.resolve()
  File "/opt/certbot/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2524, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/certbot/lib/python3.7/site-packages/certbot_dns_tencentcloud/certbot_tencentcloud_plugins.py", line 155, in <module>
    class TencentCloudClient:
  File "/opt/certbot/lib/python3.7/site-packages/certbot_dns_tencentcloud/certbot_tencentcloud_plugins.py", line 251, in TencentCloudClient
    def describe_record_list(self, domain: str) -> list[Dict]:
TypeError: 'type' object is not subscriptable
2023-08-29 03:45:28,608:ERROR:certbot._internal.log:An unexpected error occurred:
2023-08-29 03:45:28,608:ERROR:certbot._internal.log:TypeError: 'type' object is not subscriptable
```

**Nginx Proxy Manager Version**
v2.10.4 

**Operating System**
```bash
$ docker info
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

```

**Comment by zhzy0077** [comment]
It's caused by this <a title="[Fix type hinting by osirisinferi · Pull Request #5 · Frefreak/certbot-dns-tencentcloud](https://github.com/Frefreak/certbot-dns-tencentcloud/pull/5)" href="https://github.com/Frefreak/certbot-dns-tencentcloud/pull/5">Fix type hinting by osirisinferi · Pull Request #5 · Frefreak/certbot-dns-tencentcloud</a>

A mitigation is to exec into the container and `. /opt/certbot/bin/activate && pip install --no-cache-dir certbot-dns-tencentcloud==2.0.2 && deactivate`
