### ISSUE TITLE
OVH DNS Fails due to recent change in OVH JSON Response

### ISSUE THREAD

**Issue by thering1975TG** [NginxProxyManager/nginx-proxy-manager#3274]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
Due to a recent change in OVH DNS Responses as detailed in the link below, all Certbot requests using OVH DNS will fail immediately

[https://github.com/AnalogJ/lexicon/issues/1758]

Certbot version 2.7.2 includes the fix required

OVH have confirmed the change

**Nginx Proxy Manager Version**
Latest Version August 2023

**To Reproduce**
Use OVH DNS Challenge
Enter API Details
Request Cert
5 Seconds later it fails

**Expected behavior**
Challenge made and certficate issues

**Operating System**
Proxmox > Alpine Linux > Docker

**Additional context**
`Internal Error
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-15" --agree-tos --email "removed@gmail.com" --domains "my.domain.com" --authenticator dns-ovh --dns-ovh-credentials "/etc/letsencrypt/credentials/credentials-XX"
Saving debug log to /tmp/letsencrypt-log/letsencrypt.log
Error adding TXT record: Expecting value: line 1 column 1 (char 0)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details.

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`

**Comment by thering1975TG** [comment]
Can confirm upgrading with the following allows certs to renew again on OVH

`cd /opt/certbot
/opt/certbot/bin/pip install certbot==2.7.2
/opt/certbot/bin/pip install -U certbot-dns-ovh
. /opt/certbot/bin/activate && pip install --upgrade pyopenssl`

**Comment by hardwareadictos** [comment]
seems that the error is happening again, not working even with the fix above:

````
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-80" --agree-tos --email "xxxx@xxx.com" --domains "xxx.xxx.xxx" --authenticator dns-ovh --dns-ovh-credentials "/etc/letsencrypt/credentials/credentials-XX"
Saving debug log to /tmp/letsencrypt-log/letsencrypt.log
Python 3.7 support will be dropped in the next planned release of Certbot - please upgrade your Python version.
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details.

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
````

Now my nginx proxy manager is unable to renew/create new certificates. Did someone fix it?

**Comment by MilesTEG1** [comment]
Hello,
I've encountering a similar error:
```
CommandError: usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-ovh-credentials /etc/letsencrypt/credentials/credentials-2

    at /app/lib/utils.js:16:13
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

Does it exist a fix somehow ?

**Comment by hardwareadictos** [comment]
> Hello, I've encountering a similar error:
> 
> ```
> CommandError: usage: 
>   certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
> 
> Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
> it will attempt to use a webserver both for obtaining and installing the
> certificate. 
> certbot: error: unrecognized arguments: --dns-ovh-credentials /etc/letsencrypt/credentials/credentials-2
> 
>     at /app/lib/utils.js:16:13
>     at ChildProcess.exithandler (node:child_process:410:5)
>     at ChildProcess.emit (node:events:513:28)
>     at maybeClose (node:internal/child_process:1100:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
> ```
> 
> Does it exist a fix somehow ?

In my case this was fixed by my side using cnames instead of dnames on my domain provider.

Anyways I'm concerned about not getting any response on months...

**Comment by MilesTEG1** [comment]
> > Does it exist a fix somehow ?
> 
> In my case this was fixed by my side using cnames instead of dnames on my domain provider.
> 
> Anyways I'm concerned about not getting any response on months...
In my case, I already have a CNAME for *.my-ndd.ovh pointing to my-ndd.ovh.

my-ndd.ovh is a DynHost so the domain point to my IP address.

I need to find another reverse proxy to use.
