### ISSUE TITLE
Update new jc21/mariadb-aria:latest image (aac5e8d54885)"

### ISSUE THREAD

**Issue by D1skanime** [NginxProxyManager/nginx-proxy-manager#3362]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

Uable to login in on proxy manager

DBError: select certificate.* from certificate where is_deleted = 0 and provider = 'letsencrypt' - ER_NO_SUCH_TABLE: Table 'npm.certificate' doesn't exist 

 at wrapError (/app/node_modules/db-errors/lib/dbErrors.js:19:14)

    at handleExecuteError (/app/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1123:32)

    at QueryBuilder.execute (/app/node_modules/objection/lib/queryBuilder/QueryBuilder.js:449:20)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

time="2023-11-27T12:02:42Z" level=info msg="Found new jc21/mariadb-aria:latest image (aac5e8d54885)"
time="2023-11-27T12:02:42Z" level=info msg="Stopping /nginx_db_1 (88ae40385c26) with SIGTERM"
time="2023-11-27T12:02:43Z" level=info msg="Creating /nginx_db_1"

[12/2/2023] [12:22:58 PM] [Express  ] › ⚠  warning   select `user`.* from `user` where `email` = 'xxx@gmail.com' and `is_deleted` = 0 and `is_disabled` = 0 - ER_NO_SUCH_TABLE: Table 'npm.user' doesn't exist

Login is saved from Passwort manger not possible that use a wrong user ,Pw

**Nginx Proxy Manager Version**
2.10.4

**To Reproduce**
1. Go to Login page give Loginname and Passwort
2. Click on 'sigin in' Button
4. See error in red internal error

**Comment by ericmail84** [comment]
Was just updating my images, ran into this issue. Tagging to mariadb-aria:10.4.15 resolves the issue for now.
