### ISSUE TITLE
ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.7/site-packages/acme/client.py)

### ISSUE THREAD

**Issue by emign** [NginxProxyManager/nginx-proxy-manager#3414]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
```
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-21" --agree-tos --email "nicolai@emig.me" --domains "*.emig.me" --authenticator dns-namecheap --dns-namecheap-credentials "/etc/letsencrypt/credentials/credentials-21"
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in 
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in 
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 28, in 
    from certbot import crypto_util
  File "/opt/certbot/lib/python3.7/site-packages/certbot/crypto_util.py", line 42, in 
    from certbot import interfaces
  File "/opt/certbot/lib/python3.7/site-packages/certbot/interfaces.py", line 21, in 
    from acme.client import ClientBase
ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.7/site-packages/acme/client.py)

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Nginx Proxy Manager Version**

**To Reproduce**
1. Create a new SSL cert with DNS challenge

**Expected behavior**
A working SSL cert

**Screenshots**
<img width="536" alt="image" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/5278352/992c4249-d931-4243-a908-97b32d88a101">

**Operating System**
docker container

**Additional context**
Doesnt work with godaddy or durckdns either

**Comment by anatoliykmetyuk** [comment]
Encountering same issue - is there any workaround possible?

**Comment by A-CHR** [comment]
Bug seems to have gotten resolved in version 2.11.1 so can probably be closed.
