### ISSUE TITLE
Internal Server Error with flask app

### ISSUE THREAD

**Issue by jfgarciamex** [NginxProxyManager/nginx-proxy-manager#3572]
Hi, I'm trying to use ngxinx proxy manager with a flask app, but when I try to use I keep getting and Internal Server Error. For example, if I configure host.test.net to forward it to the app server, I get the following in the app log:

```
02/20/2024, 20:26:52.249   RemoteControl connection from ('172.23.0.2', 44552)
Remote Control Connected
GET remote/
[2024-02-20 20:26:52,251] ERROR in app: Exception on /remote/ [GET]
Traceback (most recent call last):
  File "/home/slingbox/.env/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slingbox/.env/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slingbox/.env/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slingbox/.env/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slingbox/slingbox_server.py", line 1578, in index
    streamer, client, remote = get_streamer( request, text )
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slingbox/slingbox_server.py", line 1520, in get_streamer
    port = request.headers.get('Host').split(':')[1]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

I think the request from nginx proxy manager is not being managed correctly by the flask app, and I guess 172.23.0.2 is the docker address. Any suggestion to fix this. Thanks!

**Comment by jfgarciamex** [comment]
Just got more details from the app developer and he just told me the issue is NGINX is not populating the "Host" information in the response. Any suggestion to fix this behavior? Thanks

**Comment by jfgarciamex** [comment]
After digging a little bit I think the problem is that the message received by the app does not include the port. So how can I the port in the redirected message, for example: host.example.com -> host:8080
