### ISSUE TITLE
Internal error (to do with NodeJS?) when trying to make an SSL certificate

### ISSUE THREAD

**Issue by Oak-Trees** [NginxProxyManager/nginx-proxy-manager#3717]
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
When trying to make an SSL certificate I get an internal error with the following error message
```
CommandError: Saving debug log to /tmp/letsencrypt-log/letsencrypt.log
An unexpected error occurred:
Error creating new order :: Cannot issue for "thuis.home": Domain name does not end with a valid public suffix (TLD)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details.

    at /app/lib/utils.js:16:13
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket. (node:internal/child_process:457:11)
    at Socket.emit (node:events:518:28)
    at Pipe. (node:net:337:12)
``` 

**Nginx Proxy Manager Version**
2.11.1

**To Reproduce**
1. Go to SSL certificates > make new certificate
2. Enter domain name
3. Enable agree to terms
4. Click save and wait

**Expected behavior**
I expect it to make a certificate succesfully

**Screenshots**
<img width="381" alt="1" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/1597919/68f8f942-5e10-43f9-81d7-61ebf8f85847">

**Operating System**
Raspberry Pi OS, version 12 64 bit on a Raspberry Pi 4

**Additional context**
Docker version 26.0.2, build 3c863ff
Portainer Community Edition 2.19.5
Firefox 124.0.2 (64-bits)

**Comment by giovanni-cm** [comment]
Same issue to me.
It is not possible to renew existing certificates and it is not possible to obtain new certificates.

**Comment by fuchs-fabian** [comment]
```
CommandError: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-duckdns/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-duckdns/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-duckdns/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-duckdns/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-duckdns/
ERROR: Could not find a version that satisfies the requirement certbot-dns-duckdns~=0.9 (from versions: none)
ERROR: No matching distribution found for certbot-dns-duckdns~=0.9

    at /app/lib/utils.js:16:13
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

I have been working on this problem for about 10 hours now. I have done everything possible. Restarted everything possible and set it up differently.

I have not been able to generate certificates for 2 days.

I am now testing the previous version again. The current version is definitely not working.

![grafik](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/113627311/7cc0151c-8285-4e91-b33a-e5fef487b0b1)

[Docker Hub](https://hub.docker.com/r/jc21/nginx-proxy-manager)

The problem occurred at the same time as the update to Docker Hub.

**Comment by giovanni-cm** [comment]
Found the culprit!!!!!!!
It is not nginx-proxy-manager, but a change of the way to work of Let's Encrypt.
Basically if you have geoblocking in your firewall, this is not allowing the automated procedure to obtain a Let's Encrypt certificate.
Please see here: https://community.letsencrypt.org/t/unexpected-renewal-failures-during-april-2024-please-read-this/216830

**Comment by Scope666** [comment]
> Found the culprit!!!!!!! It is not nginx-proxy-manager, but a change of the way to work of Let's Encrypt. Basically if you have geoblocking in your firewall, this is not allowing the automated procedure to obtain a Let's Encrypt certificate. Please see here: https://community.letsencrypt.org/t/unexpected-renewal-failures-during-april-2024-please-read-this/216830

OMG I LOVE YOU!!!!  ... ok, sorry, got too excited, but holy crap you just saved my day.  I've been fighting with this for HOURS, turns out it was Geo blocking in my Unifi gear ... I thought to check that but it wasn't logging the block on the Unifi side, so I moved on to other things.

Thanks!!!!
