### ISSUE TITLE
SSL DNS Challenge with Oraclecloud provider - issue generating SSL

### ISSUE THREAD

**Issue by leosimony** [NginxProxyManager/nginx-proxy-manager#3821]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I am trying to generate SSL using DNS Challenge with the provider Oraclecloud. I have railed the logs of the docker container and noticed it ends with an error as mentioned below. 

```
2024-06-24T07:32:38.897719032Z [6/24/2024] [7:32:38 AM] [Certbot  ] › ▶  start     Installing oci...
2024-06-24T07:32:38.897946464Z [6/24/2024] [7:32:38 AM] [Global   ] › ⬤  debug     CMD: . /opt/certbot/bin/activate && pip install --no-cache-dir oci certbot-dns-oci~=0.3.6  && deactivate
2024-06-24T07:34:03.095663277Z [6/24/2024] [7:34:03 AM] [Certbot  ] › ☒  complete  Installed oci
2024-06-24T07:34:03.095723706Z [6/24/2024] [7:34:03 AM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates via Oracle Cloud Infrastructure DNS for Cert #1: xxxxx.xxxxx.com

2024-06-24T07:34:04.155035214Z [6/24/2024] [7:34:04 AM] [Express  ] › ⚠  warning   Traceback (most recent call last):
2024-06-24T07:34:04.155087207Z   File "/opt/certbot/bin/certbot", line 5, in <module>
2024-06-24T07:34:04.155100124Z     from certbot.main import main
2024-06-24T07:34:04.155109004Z   File "/opt/certbot/lib/python3.11/site-packages/certbot/main.py", line 2, in <module>
2024-06-24T07:34:04.155118206Z     from certbot._internal import main as internal_main
2024-06-24T07:34:04.155127019Z   File "/opt/certbot/lib/python3.11/site-packages/certbot/_internal/main.py", line 26, in <module>
2024-06-24T07:34:04.155136479Z     from certbot._internal import account
2024-06-24T07:34:04.155145129Z   File "/opt/certbot/lib/python3.11/site-packages/certbot/_internal/account.py", line 16, in <module>
2024-06-24T07:34:04.155154179Z     from acme.client import ClientBase  # pylint: disable=unused-import
2024-06-24T07:34:04.155162882Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-24T07:34:04.155192228Z ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.11/site-packages/acme/client.py)
```

**Nginx Proxy Manager Version**
v2.11.2

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'SSL Certificates' and Click on "Add SSL Certificate"
2. Fill in the necessary details opt for the DNS challenge and Select OracleCloud from the drop down.
3. As per the template, provide the correct configs to authenticate with the Oracle cloud.
4. See the error in the docker logs from the command line.

**Expected behaviour**
SSL should be generated without any issues.

**Operating System** - My setup is a docker environment.
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm

**Additional context**
What I understood from this behaviour is "certbot-dns-oci~=0.3.6" module requires the certbot to be <=1.15 and pip install command uninstalls the existing version and installs the required one by certbot-dns-oci and eventually it results in 'ImportError: cannot import name 'ClientBase'' error. If I do pip install --upgrade certbot then it works fine. The compatibility of DNS oci module with certbot seems to be an issue. Can this be addressed?

**Comment by PaserSRL** [comment]
I have the same issue, I cannot generate wildcard certificated using Oracle DNS.
