### ISSUE TITLE
Invalid ipv6 resolver address

### ISSUE THREAD

**Issue by tknx** [NginxProxyManager/nginx-proxy-manager#392]
Updated to latest docker recently and now the docker won't launch.

- A clear and concise description of what the bug is.

Logs show the following error:

```
[nginx] starting...
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
```
- What version of Nginx Proxy Manager is reported on the login page?

Can't see but just updated

**Operating System**

- Unraid (Slackware)

**Additional context**

I tried removing the offending address directly from the conf file but it seemed to add it back

**Comment by tknx** [comment]
Excerpt from logs here:

`Version: '10.3.22-MariaDB' socket: '/run/mysqld/mysqld.sock' port: 3306 MariaDB Server

[services.d] starting nginx...
[services.d] starting app...
[nginx] starting...
[app] starting Nginx Proxy Manager...
[services.d] done.
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
[nginx] starting...
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
[5/2/2020] [9:30:39 AM] [Migrate ] › ℹ info Current database version: 20200410143839

[5/2/2020] [9:30:39 AM] [IP Ranges] › ℹ info Fetching IP Ranges from online services...
[5/2/2020] [9:30:39 AM] [IP Ranges] › ℹ info Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[nginx] starting...
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
[5/2/2020] [9:30:39 AM] [IP Ranges] › ℹ info Fetching https://www.cloudflare.com/ips-v4
[5/2/2020] [9:30:39 AM] [IP Ranges] › ℹ info Fetching https://www.cloudflare.com/ips-v6
[5/2/2020] [9:30:39 AM] [SSL ] › ℹ info Let's Encrypt Renewal Timer initialized
[5/2/2020] [9:30:39 AM] [SSL ] › ℹ info Renewing SSL certs close to expiry...
[5/2/2020] [9:30:39 AM] [IP Ranges] › ℹ info IP Ranges Renewal Timer initialized
[5/2/2020] [9:30:39 AM] [Global ] › ℹ info Backend PID 1645 listening on port 3000 ...
[nginx] starting...
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
[nginx] starting...
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
[nginx] starting...
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
[5/2/2020] [9:30:42 AM] [SSL ] › ✖ error Error: Command failed: /usr/sbin/nginx -t

nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed


at ChildProcess.exithandler (child_process.js:294:12)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
[nginx] starting...
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
[nginx] starting...
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1
[nginx] starting...
nginx: [emerg] invalid
`

**Comment by johntdavis84** [comment]
I'm having this issue when trying to bring up the container with `docker-compose -up`, as well. 

I'm less experienced with docker than others, and I'm not even sure where the /etc/nginx/conf.d/ directory is supposed to be. Is it in a container? On the host server? I looked on my Pi, and there's no conf.d folder in the /etc/nginx directory in the host filesystem.

**Comment by JonasVgt** [comment]
This is probably the same issue i am having at #1015

**Comment by LordChunk** [comment]
Not sure if this **workaround** is good practice, but I resolved this issue by doing the following.

- Attach to your docker container running Nginx Proxy Manager and run ``ifconfig``
- Copy the local IPv6 address
![image](https://user-images.githubusercontent.com/23651869/120002634-5500ff00-bfd5-11eb-94eb-3abb201d9b35.png)
- Open ``/config/nginx/resolvers.conf`` 
- Replace the current IPv6 address in the brackets with the one you copied in step 2.
Your file should look something like this.
![image](https://user-images.githubusercontent.com/23651869/120002508-33077c80-bfd5-11eb-8a7f-56b2f6f9a764.png)
- Save the file and you should be done (in my case I didn't have to restart the container).

**Comment by phrogg** [comment]
> * /config/nginx/resolvers.conf

I can confirm this worked for me! But I had to change the path of the file. `/etc/nginx/conf.d/include/resolvers.conf`.

Also the file was overwritten really fast and I head to manipulate it several times, to get it to work.

**Comment by LordChunk** [comment]
> > * /config/nginx/resolvers.conf
> 
> I can confirm this worked for me! But I had to change the path of the file. `/etc/nginx/conf.d/include/resolvers.conf`.
> 
> Also the file was overwritten really fast and I head to manipulate it several times, to get it to work.

Oh, I didn't have that issue. I'm running it on Docker, so the behaviour might be somewhat different to your situation.

**Comment by phrogg** [comment]
> > > * /config/nginx/resolvers.conf
> > 
> > 
> > I can confirm this worked for me! But I had to change the path of the file. `/etc/nginx/conf.d/include/resolvers.conf`.
> > Also the file was overwritten really fast and I head to manipulate it several times, to get it to work.
> 
> Oh, I didn't have that issue. I'm running it on Docker, so the behaviour might be somewhat different to your situation.

Yeah I'm running it on docker as well.
