### ISSUE TITLE
Impossible to upload custom certificate

### ISSUE THREAD

**Issue by trisosamu** [NginxProxyManager/nginx-proxy-manager#4008]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - No

**Describe the bug**

**Nginx Proxy Manager Version**

**To Reproduce**
1. Go to 'SSL Certificate'
2. Click on '.Ass SSL Certificate'
3. Scroll down to '.Custom'
4. Upload all file with .pem extension

**Screenshots**

**Operating System**

**Comment by SQ9MDD** [comment]
Same issue here

I’m experiencing the exact same problem.
When I try to add a custom certificate, the Certificates interface freezes or breaks — it stops loading completely afterward.

I tried uploading valid .pem and key files, but after clicking Save the UI hangs and the certificate never appears. Restarting the container or clearing cache doesn’t help.

**Comment by moseslecce** [comment]
When I try to upload a custom wildcard certificate, I notice in the logs it does not include a domain name:

id: 12,
expires_on: '2026-07-21 23:59:59',
domain_names: [ null ]

and upon reloading the certificate page it will go blank due to an error:

Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at h (DomainsFormatter-DRGLydBn.js:1:109)
    at ld (index-BBAG1AZl.js:49:48769)
    at M0 (index-BBAG1AZl.js:49:71656)
    at nS (index-BBAG1AZl.js:49:82048)
    at LS (index-BBAG1AZl.js:49:117928)
    at aI (index-BBAG1AZl.js:49:116966)
    at tg (index-BBAG1AZl.js:49:116794)
    at xS (index-BBAG1AZl.js:49:113564)
    at qS (index-BBAG1AZl.js:49:125603)
    at Ad (index-BBAG1AZl.js:49:124155)


Here is the relevant code snippet:

import {j as e, d as c, ad as m, c as d} from "./index-BBAG1AZl.js";
const h = ({domain: s, color: n}) => {
    let a;
    return s.includes("*") && (a = l => l.preventDefault()),
    e.jsx("a", {
        href: `http://${s}`,
        target: "_blank",
        onClick: a,
        className: d("badge", n ? `bg-${n}-lt` : null, "domain-name", "me-2"),
        children: s
    }, s)
}
