### ISSUE TITLE
Certbot is already runnning. 

### ISSUE THREAD

**Issue by GogoFC** [NginxProxyManager/nginx-proxy-manager#4059]
Hello

**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Well No because there are usually breaking changes.
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes. No mention of Certbot

**Describe the bug**
Stopped being able to obtain SSL certs.
Double checked if I misspelled the domain by trying to obtain a cert for a working domain. Working domain cert got deleted and new cert wasn't obtained.

Back to the Bug. It just says Certbot is already running.

**Nginx Proxy Manager Version**
jc21/nginx-proxy-manager:2.10.2 

**Operating System**
Ubuntu 22.04

**Additional context**

**yaml**
```yaml
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.10.2'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
#      - '8888:8888' # 80 on laptop
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
#      - '636:636'
#      - '88:88'
#      - '464:464'
#      - '389:389'
    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      #- DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  default:
    name: mreza
    external: true
```

**docker compose logs**
These logs is when I tried to renew a known working domains.
```
app-1  | Another instance of Certbot is already running.
app-1  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-vkjgbv3n/log or re-run Certbot with -v for more details.
app-1  | 
app-1  | [10/12/2024] [2:06:40 AM] [Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/16.conf
app-1  | [10/12/2024] [2:06:40 AM] [Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/16.conf.err
app-1  | [10/12/2024] [2:06:40 AM] [Nginx    ] › ⬤  debug     Could not delete file: {
app-1  |   "errno": -2,
app-1  |   "syscall": "unlink",
app-1  |   "code": "ENOENT",
app-1  |   "path": "/data/nginx/proxy_host/16.conf.err"
app-1  | }
app-1  | [10/12/2024] [2:06:40 AM] [Nginx    ] › ℹ  info      Reloading Nginx
app-1  | [10/12/2024] [2:06:45 AM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #51: psgnctest.domain.com
app-1  | [10/12/2024] [2:06:45 AM] [SSL      ] › ℹ  info      Command: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-51" --agree-tos --authenticator webroot --email "me@gmail.com" --preferred-challenges "dns,http" --domains "psgnctest.domain.com" 
app-1  | [10/12/2024] [2:06:45 AM] [Nginx    ] › ⬤  debug     Deleting file: /data/nginx/temp/letsencrypt_51.conf
app-1  | [10/12/2024] [2:06:46 AM] [Nginx    ] › ℹ  info      Reloading Nginx
app-1  | [10/12/2024] [2:06:46 AM] [Express  ] › ⚠  warning   Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-51" --agree-tos --authenticator webroot --email "me@gmail.com" --preferred-challenges "dns,http" --domains "psgnctest.domain.com" 
app-1  | Another instance of Certbot is already running.
app-1  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-u0zmkhz9/log or re-run Certbot with -v for more details.
app-1  | 
app-1  | [10/12/2024] [2:07:23 AM] [Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/3.conf
app-1  | [10/12/2024] [2:07:23 AM] [Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/3.conf.err
app-1  | [10/12/2024] [2:07:23 AM] [Nginx    ] › ⬤  debug     Could not delete file: {
app-1  |   "errno": -2,
app-1  |   "syscall": "unlink",
app-1  |   "code": "ENOENT",
app-1  |   "path": "/data/nginx/proxy_host/3.conf.err"
app-1  | }
app-1  | [10/12/2024] [2:07:23 AM] [Nginx    ] › ℹ  info      Reloading Nginx
app-1  | [10/12/2024] [2:07:28 AM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #52: cloud.domain.com
app-1  | [10/12/2024] [2:07:28 AM] [SSL      ] › ℹ  info      Command: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-52" --agree-tos --authenticator webroot --email "me@gmail.com" --preferred-challenges "dns,http" --domains "cloud.domain.com" 
app-1  | [10/12/2024] [2:07:29 AM] [Nginx    ] › ⬤  debug     Deleting file: /data/nginx/temp/letsencrypt_52.conf
app-1  | [10/12/2024] [2:07:29 AM] [Nginx    ] › ℹ  info      Reloading Nginx
app-1  | [10/12/2024] [2:07:29 AM] [Express  ] › ⚠  warning   Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-52" --agree-tos --authenticator webroot --email "me@gmail.com" --preferred-challenges "dns,http" --domains "cloud.domain.com" 
app-1  | Another instance of Certbot is already running.
app-1  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-327zucpp/log or re-run Certbot with -v for more details.
app-1  | 
```

**Logs from inside container**
```
2024-10-12 02:01:54,865:DEBUG:certbot._internal.main:certbot version: 2.4.0
2024-10-12 02:01:54,866:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2024-10-12 02:01:54,866:DEBUG:certbot._internal.main:Arguments: ['--config', '/etc/letsencrypt.ini', '--work-dir', '/tmp/letsencrypt-lib', '--logs-dir', '/tmp/letsencrypt-log', '--cert-name', 'npm-49', '--agree-tos', '--authenticator', 'webroot', '--email', 'me@gmail.com', '--preferred-challenges', 'dns,http', '--domains', 'syncthing0.domain.com']
2024-10-12 02:01:54,866:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-10-12 02:01:54,873:DEBUG:certbot._internal.lock:A lock on /tmp/letsencrypt-log/.certbot.lock is held by another process.
2024-10-12 02:01:54,874:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/lock.py", line 126, in _try_lock
    fcntl.lockf(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1854, in main
    log.post_arg_parse_setup(config)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/log.py", line 108, in post_arg_parse_setup
    config, 'letsencrypt.log', FILE_FMT)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/log.py", line 161, in setup_log_file_handler
    util.set_up_core_dir(config.logs_dir, 0o700, config.strict_permissions)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/util.py", line 188, in set_up_core_dir
    lock_dir_until_exit(directory)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/util.py", line 162, in lock_dir_until_exit
    _LOCKS[dir_path] = lock.lock_dir(dir_path)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/lock.py", line 259, in lock_dir
    return LockFile(os.path.join(dir_path, '.certbot.lock'))
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/lock.py", line 45, in __init__
    self.acquire()
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/lock.py", line 60, in acquire
    self._lock_mechanism.acquire()
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/lock.py", line 112, in acquire
    self._try_lock(fd)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/lock.py", line 130, in _try_lock
    raise errors.LockError('Another instance of Certbot is already running.')
certbot.errors.LockError: Another instance of Certbot is already running.
2024-10-12 02:01:54,874:ERROR:certbot._internal.log:Another instance of Certbot is already running.
[root@docker-38c2d2f48b5f:/tmp/certbot-log-viwipeo3]# 
```

**Logs arter container restart**
```
app-1  | Another instance of Certbot is already running.
app-1  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-u0zmkhz9/log or re-run Certbot with -v for more details.
app-1  | 
app-1  | [10/12/2024] [2:07:23 AM] [Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/3.conf
app-1  | [10/12/2024] [2:07:23 AM] [Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/3.conf.err
app-1  | [10/12/2024] [2:07:23 AM] [Nginx    ] › ⬤  debug     Could not delete file: {
app-1  |   "errno": -2,
app-1  |   "syscall": "unlink",
app-1  |   "code": "ENOENT",
app-1  |   "path": "/data/nginx/proxy_host/3.conf.err"
app-1  | }
app-1  | [10/12/2024] [2:07:23 AM] [Nginx    ] › ℹ  info      Reloading Nginx
app-1  | [10/12/2024] [2:07:28 AM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #52: cloud.domain.com
app-1  | [10/12/2024] [2:07:28 AM] [SSL      ] › ℹ  info      Command: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-52" --agree-tos --authenticator webroot --email "me@gmail.com" --preferred-challenges "dns,http" --domains "cloud.domain.com" 
app-1  | [10/12/2024] [2:07:29 AM] [Nginx    ] › ⬤  debug     Deleting file: /data/nginx/temp/letsencrypt_52.conf
app-1  | [10/12/2024] [2:07:29 AM] [Nginx    ] › ℹ  info      Reloading Nginx
app-1  | [10/12/2024] [2:07:29 AM] [Express  ] › ⚠  warning   Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-52" --agree-tos --authenticator webroot --email "me@gmail.com" --preferred-challenges "dns,http" --domains "cloud.domain.com" 
app-1  | Another instance of Certbot is already running.
app-1  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-327zucpp/log or re-run Certbot with -v for more details.
app-1  | 
app-1  | [10/12/2024] [2:08:58 AM] [SSL      ] › ✖  error     Error: Command failed: certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --preferred-challenges "dns,http" --disable-hook-validation  
app-1  | Failed to renew certificate npm-11 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-12 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-14 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-17 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-18 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-21 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-23 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-4 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-5 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-7 with error: Some challenges have failed.
app-1  | Failed to renew certificate npm-9 with error: Some challenges have failed.
app-1  | All renewals failed. The following certificates could not be renewed:
app-1  |   /etc/letsencrypt/live/npm-11/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-12/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-14/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-17/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-18/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-21/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-23/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-4/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-5/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-7/fullchain.pem (failure)
app-1  |   /etc/letsencrypt/live/npm-9/fullchain.pem (failure)
app-1  | 11 renew failure(s), 0 parse failure(s)
app-1  | 
app-1  |     at ChildProcess.exithandler (node:child_process:402:12)
app-1  |     at ChildProcess.emit (node:events:513:28)
app-1  |     at maybeClose (node:internal/child_process:1100:16)
app-1  |     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by Guiorgy** [comment]
> Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
> * Well No because there are usually breaking changes.

Can anybody help you?
* Well No because it's not clear if this is still a problem, or it has been fixed in a later update.

Please, try the latest image before reporting. If you have to, you can backup the old container volume and restore it after.
