### ISSUE TITLE
Error Certbot add DNS Challenge witch OVH

### ISSUE THREAD

**Issue by kwetnico** [NginxProxyManager/nginx-proxy-manager#4191]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes / 
- Are you sure you're not using someone else's docker image?
  - Yes / 
- Have you searched for similar issues (both open and closed)?
  - Yes / 

**Describe the bug**

**Nginx Proxy Manager Version**
2.12.1

![image](https://github.com/user-attachments/assets/a97a693f-d572-4da1-bbcf-33f99581f691)

**Operating System**

 -->

**Comment by badkeyy** [comment]
I can't reproduce this however it get the following error for OVH's EU Endpoint:
`CommandError: Saving debug log to /tmp/letsencrypt-log/letsencrypt.log
Unexpected error determining zone identifier for test.gassner-it.at: HTTPSConnectionPool(host='eu.api.ovh.com', port=443): Max retries exceeded with url: /1.0/auth/time (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:992)')))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details.

    at /app/lib/utils.js:16:13
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)`

**Comment by badkeyy** [comment]
Can't reproduce. For me this works fine

**Comment by jmatraszek** [comment]
I have the same issue — just installed npm in LXC containter in Proxmox and had the same error message. Tried installing certbot plugins by running `app/scripts/install-certbot-plugins`, but installing `ovh` plugin fails with this error:

```
[Certbot  ] › ▶  start     Installing ovh...
[Global   ] › ⬤  debug     CMD: . /opt/certbot/bin/activate && pip install --no-cache-dir acme==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') certbot-dns-ovh==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+')  && deactivate
[Certbot  ] › ✖  error     Traceback (most recent call last):
  File "/opt/certbot/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/opt/certbot/lib/python3.11/site-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.11/site-packages/certbot/_internal/main.py", line 26, in <module>
    from certbot._internal import account
  File "/opt/certbot/lib/python3.11/site-packages/certbot/_internal/account.py", line 16, in <module>
    from acme.client import ClientBase  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.11/site-packages/acme/client.py)
Traceback (most recent call last):
  File "/opt/certbot/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/opt/certbot/lib/python3.11/site-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.11/site-packages/certbot/_internal/main.py", line 26, in <module>
    from certbot._internal import account
  File "/opt/certbot/lib/python3.11/site-packages/certbot/_internal/account.py", line 16, in <module>
    from acme.client import ClientBase  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.11/site-packages/acme/client.py)
ERROR: Could not find a version that satisfies the requirement acme== (from versions: 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104, 0.0.0.dev20151107, 0.0.0.dev20151108, 0.0.0.dev20151114, 0.0.0.dev20151123, 0.0.0.dev20151201, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.18.1, 0.18.2, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.22.0, 0.22.1, 0.22.2, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.26.0, 0.26.1, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.29.1, 0.30.0, 0.30.1, 0.30.2, 0.31.0, 0.32.0, 0.33.0, 0.33.1, 0.34.0, 0.34.1, 0.34.2, 0.35.0, 0.35.1, 0.36.0, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.39.0, 0.40.0, 0.40.1, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.25.0, 1.26.0, 1.27.0, 1.28.0, 1.29.0, 1.30.0, 1.31.0, 1.32.0, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0, 2.9.0, 2.10.0, 2.11.0, 3.0.0, 3.0.1)
ERROR: No matching distribution found for acme==
```

**Comment by Wendigogo** [comment]
Got that too.

Seems like certbot-dns-ovh is not up ta date : [](https://pypi.org/project/certbot-dns-ovh/#history).
Maybe that's why certbot-dns-ovh requires an acme-2 while others require an acme-3 version.

Switching to latest certbot-dns-ovh version could solve this issue.

Enjoy!

**Comment by Wendigogo** [comment]
Trying to force certbot-dns-ovh version leads to this :
` . /opt/certbot/bin/activate && pip install --no-cache-dir  certbot-dns-ovh~=3.0.1  && deactivate
Collecting certbot-dns-ovh~=3.0.1
  Downloading certbot_dns_ovh-3.0.1-py3-none-any.whl (10 kB)
Collecting dns-lexicon>=3.15.1
  Downloading dns_lexicon-3.18.0-py3-none-any.whl (248 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.5/248.5 kB 8.5 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=41.6.0 in /opt/certbot/lib/python3.11/site-packages (from certbot-dns-ovh~=3.0.1) (74.0.0)
Requirement already satisfied: acme>=3.0.1 in /opt/certbot/lib/python3.11/site-packages (from certbot-dns-ovh~=3.0.1) (3.0.1)
Collecting certbot>=3.0.1
  Downloading certbot-3.0.1-py3-none-any.whl (407 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.5/407.5 kB 35.6 MB/s eta 0:00:00
Requirement already satisfied: cryptography>=3.2.1 in /opt/certbot/lib/python3.11/site-packages (from acme>=3.0.1->certbot-dns-ovh~=3.0.1) (3.4.8)
Requirement already satisfied: josepy<2,>=1.13.0 in /opt/certbot/lib/python3.11/site-packages (from acme>=3.0.1->certbot-dns-ovh~=3.0.1) (1.14.0)
Requirement already satisfied: PyOpenSSL!=23.1.0,>=17.5.0 in /opt/certbot/lib/python3.11/site-packages (from acme>=3.0.1->certbot-dns-ovh~=3.0.1) (21.0.0)
Requirement already satisfied: pyrfc3339 in /usr/lib/python3/dist-packages (from acme>=3.0.1->certbot-dns-ovh~=3.0.1) (1.1)
Requirement already satisfied: pytz>=2019.3 in /opt/certbot/lib/python3.11/site-packages (from acme>=3.0.1->certbot-dns-ovh~=3.0.1) (2024.1)
Requirement already satisfied: requests>=2.20.0 in /opt/certbot/lib/python3.11/site-packages (from acme>=3.0.1->certbot-dns-ovh~=3.0.1) (2.32.3)
Requirement already satisfied: ConfigArgParse>=1.5.3 in /opt/certbot/lib/python3.11/site-packages (from certbot>=3.0.1->certbot-dns-ovh~=3.0.1) (1.7)
Requirement already satisfied: configobj>=5.0.6 in /usr/lib/python3/dist-packages (from certbot>=3.0.1->certbot-dns-ovh~=3.0.1) (5.0.8)
Requirement already satisfied: distro>=1.0.1 in /opt/certbot/lib/python3.11/site-packages (from certbot>=3.0.1->certbot-dns-ovh~=3.0.1) (1.9.0)
Requirement already satisfied: parsedatetime>=2.4 in /usr/lib/python3/dist-packages (from certbot>=3.0.1->certbot-dns-ovh~=3.0.1) (2.6)
Requirement already satisfied: beautifulsoup4>=4 in /usr/lib/python3/dist-packages (from dns-lexicon>=3.15.1->certbot-dns-ovh~=3.0.1) (4.11.2)
Requirement already satisfied: dnspython>=2 in /opt/certbot/lib/python3.11/site-packages (from dns-lexicon>=3.15.1->certbot-dns-ovh~=3.0.1) (2.7.0)
Requirement already satisfied: pyotp>=2 in /opt/certbot/lib/python3.11/site-packages (from dns-lexicon>=3.15.1->certbot-dns-ovh~=3.0.1) (2.9.0)
Requirement already satisfied: pyyaml>=3 in /opt/certbot/lib/python3.11/site-packages (from dns-lexicon>=3.15.1->certbot-dns-ovh~=3.0.1) (5.3.1)
Requirement already satisfied: tldextract>=2 in /opt/certbot/lib/python3.11/site-packages (from dns-lexicon>=3.15.1->certbot-dns-ovh~=3.0.1) (3.5.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from configobj>=5.0.6->certbot>=3.0.1->certbot-dns-ovh~=3.0.1) (1.16.0)
Requirement already satisfied: cffi>=1.12 in /opt/certbot/lib/python3.11/site-packages (from cryptography>=3.2.1->acme>=3.0.1->certbot-dns-ovh~=3.0.1) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/certbot/lib/python3.11/site-packages (from requests>=2.20.0->acme>=3.0.1->certbot-dns-ovh~=3.0.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/certbot/lib/python3.11/site-packages (from requests>=2.20.0->acme>=3.0.1->certbot-dns-ovh~=3.0.1) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/certbot/lib/python3.11/site-packages (from requests>=2.20.0->acme>=3.0.1->certbot-dns-ovh~=3.0.1) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/certbot/lib/python3.11/site-packages (from requests>=2.20.0->acme>=3.0.1->certbot-dns-ovh~=3.0.1) (2024.8.30)
Requirement already satisfied: requests-file>=1.4 in /opt/certbot/lib/python3.11/site-packages (from tldextract>=2->dns-lexicon>=3.15.1->certbot-dns-ovh~=3.0.1) (2.1.0)
Requirement already satisfied: filelock>=3.0.8 in /opt/certbot/lib/python3.11/site-packages (from tldextract>=2->dns-lexicon>=3.15.1->certbot-dns-ovh~=3.0.1) (3.16.1)
Requirement already satisfied: pycparser in /opt/certbot/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=3.2.1->acme>=3.0.1->certbot-dns-ovh~=3.0.1) (2.22)
Installing collected packages: dns-lexicon, certbot, certbot-dns-ovh
  Attempting uninstall: dns-lexicon
    Found existing installation: dns-lexicon 3.5.6
    Uninstalling dns-lexicon-3.5.6:
      Successfully uninstalled dns-lexicon-3.5.6
  Attempting uninstall: certbot
    Found existing installation: certbot 2.11.0
    Uninstalling certbot-2.11.0:
      Successfully uninstalled certbot-2.11.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
certbot-dns-timeweb 1.0.1 requires certbot<3.0,>=2.8, but you have certbot 3.0.1 which is incompatible.
certbot-dns-websupport 2.0.1 requires certbot<3.0.0,>=2.0.0, but you have certbot 3.0.1 which is incompatible.
certbot-dns-porkbun 0.9.1 requires tldextract<6.0,>=5.1.2, but you have tldextract 3.5.0 which is incompatible.
certbot-dns-constellix 0.2.2 requires certbot<3.0,>=2.0, but you have certbot 3.0.1 which is incompatible.
certbot-dns-cloudns 0.6.0 requires acme<2.8.0,>=2.7.4, but you have acme 3.0.1 which is incompatible.
certbot-dns-cloudns 0.6.0 requires certbot<2.8.0,>=2.7.4, but you have certbot 3.0.1 which is incompatible.
certbot-dns-oci 0.3.6 requires certbot<=1.15.0, but you have certbot 3.0.1 which is incompatible.
certbot-dns-mijn-host 0.0.5 requires acme==2.11.0, but you have acme 3.0.1 which is incompatible.
certbot-dns-mijn-host 0.0.5 requires certbot==2.11.0, but you have certbot 3.0.1 which is incompatible.
certbot-dns-mijn-host 0.0.5 requires pyOpenSSL==24.2.1, but you have pyopenssl 21.0.0 which is incompatible.
certbot-dns-powerdns 0.2.1 requires dns-lexicon<=3.5.6,>=3.2.4, but you have dns-lexicon 3.18.0 which is incompatible.
certbot-dns-dynu 0.0.4 requires dns-lexicon==3.11.7, but you have dns-lexicon 3.18.0 which is incompatible.
Successfully installed certbot-3.0.1 certbot-dns-ovh-3.0.1 dns-lexicon-3.18.0`

So It looks like you have to choose which certbot version you want depending on your provider.

As an enhancement, I would suggest to install only user related certbot-dns provider, by passing it as an argument to installation script. I don't see the point of having all these unused ones installed on my LXC.

**Comment by jmatraszek** [comment]
Hey @Wendigogo, I was able to install OVH plugin by the command you provided, however this did not fix the original error, and I was unable to obtain a certificate. Did it work for you?

**Comment by Wendigogo** [comment]
I didn't try it atm. I'm not at home and I don't want to break things now. ^_^

Maybe you should try with original version with:
`. /opt/certbot/bin/activate && pip install --no-cache-dir certbot-dns-ovh~=2.11.0 && deactivate`
Maybe that's why script stucks to this version.

**Comment by Wendigogo** [comment]
Oh my!

I just see that you could install ONLY wanted certbot plugins in looking to the script:

> // Usage:
> //   Install all plugins defined in `certbot-dns-plugins.json`:
> //    ./install-certbot-plugins
> //   **Install one or more specific plugins:**
> //    ./install-certbot-plugins route53 cloudflare

So I made a clean install (thanks proxmox) and only use `./install-certbot-plugins ovh`.

No issue in installing but `certbot plugins` still doesn't show ovh plugin. 😭

**Comment by jmatraszek** [comment]
Running `certbot plugins` gave me an idea to use MultiDns provider with the following config:
```
dns_multi_provider=ovh
OVH_ENDPOINT=ovh-eu
OVH_APPLICATION_KEY=XXX
OVH_APPLICATION_SECRET=XXX
OVH_CONSUMER_KEY=XXX
```

This way, I could generate a cert successfully! Thanks, @Wendigogo.

**Comment by Wendigogo** [comment]
> This way, I could generate a cert successfully! Thanks, @Wendigogo.
From the GUI?

I find something:
When installing plugins with `/app/scripts/install-certbot-plugins` there is a king of chroot and they are installed in `/opt/certbot/lib/python3.11/site-packages/` instead of `/usr/local/lib/python3.11/dist-packages/`. That's why modules are not seen in "normal" shell.

And if you look in `/usr/local/lib/python3.11/dist-packages/`, the ONLY available module is `certbot_dns_multi`.

So MAYBE, the npm envirronement is not set correctly. I'm using an LXC in proxmox using [this script for installation:](https://community-scripts.github.io/ProxmoxVE/scripts?id=nginxproxymanager).

**Comment by kwetnico** [comment]
> > This way, I could generate a cert successfully! Thanks, @Wendigogo.
> 
> From the GUI?
> 
> I find something: When installing plugins with `/app/scripts/install-certbot-plugins` there is a king of chroot and they are installed in `/opt/certbot/lib/python3.11/site-packages/` instead of `/usr/local/lib/python3.11/dist-packages/`. That's why modules are not seen in "normal" shell.
> 
> And if you look in `/usr/local/lib/python3.11/dist-packages/`, the ONLY available module is `certbot_dns_multi`.
> 
> So MAYBE, the npm envirronement is not set correctly. I'm using an LXC in proxmox using [this script for installation:](https://community-scripts.github.io/ProxmoxVE/scripts?id=nginxproxymanager).

For information I have the problem with ovh, I use the same version as you with proxmox and the lxc script

**Comment by kwetnico** [comment]
> dns_multi_provider=ovh

I tested with your solution: Multi Dns provider and same problem with DNS Challenge

![image](https://github.com/user-attachments/assets/78a3bced-dea4-4cba-b0d0-9f0e6118f203)

```
CommandError: usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-ovh-credentials /etc/letsencrypt/credentials/credentials-11

    at /app/lib/utils.js:16:13
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by jmatraszek** [comment]
> 
> From the GUI?
>
 
Yes, from the GUI.

> 
> So MAYBE, the npm envirronement is not set correctly. I'm using an LXC in proxmox using [this script for installation:](https://community-scripts.github.io/ProxmoxVE/scripts?id=nginxproxymanager).

I also use LXC in proxmox with nginxproxymanager installed from the same script.

> > dns_multi_provider=ovh
> 
> I tested with your solution: Multi Dns provider and same problem with DNS Challenge
> 

@kwetnico You sure you selected the `MultiDns` provider? The screenshot shows `OVH`.

**Comment by kwetnico** [comment]
> > From the GUI?
> 
> Yes, from the GUI.
> 
> > So MAYBE, the npm envirronement is not set correctly. I'm using an LXC in proxmox using [this script for installation:](https://community-scripts.github.io/ProxmoxVE/scripts?id=nginxproxymanager).
> 
> I also use LXC in proxmox with nginxproxymanager installed from the same script.
> 
> > > dns_multi_provider=ovh
> > 
> > 
> > I tested with your solution: Multi Dns provider and same problem with DNS Challenge
> 
> @kwetnico You sure you selected the `MultiDns` provider? The screenshot shows `OVH`.

Yes it's ok to ovh with DNSMulti !

**Comment by philj0st** [comment]
i still have this issue with NPM v2.12.6.
I could get it to work with the DnsMulti plugin instead of using DuckDNS or deSEC ones.
