### ISSUE TITLE
NPM stopped working, no login, no cert refresh

### ISSUE THREAD

**Issue by Tamas92** [NginxProxyManager/nginx-proxy-manager#4198]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
None of my SSL certs are valid furthermore I cannot login to the npm admin interface I got Bad Gateway error. Tried everything what I could see here in the issues. Downgrade back to 2.10.4 etc, nothing worked.

**Nginx Proxy Manager Version**
2.12.1

**To Reproduce**

**Operating System**
Debian

**Additional context**
I configured everything about 2years ago and didn't touch the system. Watchtower is upgrading the docker container automatically.

nginx-proxy-manager  | [12/1/2024] [10:42:26 AM] [Global   ] › ℹ  info      Using Sqlite: /data/database.sqlite
nginx-proxy-manager  | [12/1/2024] [10:42:26 AM] [Migrate  ] › ℹ  info      Current database version: none
nginx-proxy-manager  | [12/1/2024] [10:42:26 AM] [Global   ] › ⬤  debug     CMD: [ -f '/etc/letsencrypt/credentials/credentials-6' ] || { mkdir -p /etc/letsencrypt/credentials 2> /dev/null; echo '# Cloudflare API token
nginx-proxy-manager  | dns_cloudflare_api_token = xyz' > '/etc/letsencrypt/credentials/credentials-6' && chmod 600 '/etc/letsencrypt/credentials/credentials-6'; }
nginx-proxy-manager  | [12/1/2024] [10:42:26 AM] [Certbot  ] › ▶  start     Installing cloudflare...
nginx-proxy-manager  | [12/1/2024] [10:42:26 AM] [Global   ] › ⬤  debug     CMD: . /opt/certbot/bin/activate && pip install --no-cache-dir cloudflare==2.19.* acme==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') certbot-dns-cloudflare==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+')  && deactivate

nginx-proxy-manager  | WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffa7c99b410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cloudflare/
nginx-proxy-manager  | ERROR: Could not find a version that satisfies the requirement cloudflare==2.19.* (from versions: none)
nginx-proxy-manager  | ERROR: No matching distribution found for cloudflare==2.19.*
nginx-proxy-manager  | 
nginx-proxy-manager  | [12/1/2024] [10:46:29 AM] [Global   ] › ✖  error     Some plugins failed to install. Please check the logs above CommandError: Some plugins failed to install. Please check the logs above
nginx-proxy-manager  |     at /app/lib/certbot.js:39:14
nginx-proxy-manager  |     at Immediate.<anonymous> (/app/node_modules/batchflow/lib/batchflow.js:80:9)
nginx-proxy-manager  |     at process.processImmediate (node:internal/timers:483:21) {
nginx-proxy-manager  |   previous: undefined,
nginx-proxy-manager  |   code: 1,
nginx-proxy-manager  |   public: false
nginx-proxy-manager  | }
nginx-proxy-manager  | [12/1/2024] [10:46:30 AM] [Migrate  ] › ℹ  info      Current database version: none
nginx-proxy-manager  | [12/1/2024] [10:46:30 AM] [Global   ] › ⬤  debug     CMD: [ -f '/etc/letsencrypt/credentials/credentials-6' ] || { mkdir -p /etc/letsencrypt/credentials 2> /dev/null; echo '# Cloudflare API token
nginx-proxy-manager  | dns_cloudflare_api_token = xyz' > '/etc/letsencrypt/credentials/credentials-6' && chmod 600 '/etc/letsencrypt/credentials/credentials-6'; }
nginx-proxy-manager  | [12/1/2024] [10:46:30 AM] [Certbot  ] › ▶  start     Installing cloudflare...
nginx-proxy-manager  | [12/1/2024] [10:46:30 AM] [Global   ] › ⬤  debug     CMD: . /opt/certbot/bin/activate && pip install --no-cache-dir cloudflare==2.19.* acme==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') certbot-dns-cloudflare==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+')  && deactivate

fallback_error.log:

2024/12/01 10:32:51 [error] 234#234: *339 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.11, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "npm.myserver.net", referrer: "https://npm.myserver.net/login"
2024/12/01 10:32:52 [error] 232#232: *342 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.11, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "npm.myserver.net", referrer: "https://npm.myserver.net/login"
2024/12/01 10:32:53 [error] 229#229: *345 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.11, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "npm.myserver.net", referrer: "https://npm.myserver.net/login"

**Comment by GLLM** [comment]
Same error here.
Never had an issue for years.
Suddenly, NPM stops working. (I have a PiHole DNS working along with it)

**Comment by EikeiDev** [comment]
I caught the same error on v2.12.3

**Comment by Tamas92** [comment]
I found a workaround. I don't know why is it working like this as I'm not a docker expert.

For the pihole compose.yml I modified the ports:
From this:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"

To this:
    ports:
      - "**192.168.x.y:**53:53/tcp"
      - "**192.168.x.y:**53:53/udp"
      - "8080:80/tcp"

 192.168.x.y is the IP of my server. After that the NPM is working again.
