### ISSUE TITLE
Why I have this error when create certificate

### ISSUE THREAD

**Issue by Jamyz** [NginxProxyManager/nginx-proxy-manager#895]
```
Error: Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-20" --agree-tos --email "j***************@gmail.com" --preferred-challenges "dns,http" --domains "haproxy.mydomain.com" 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for haproxy.mydomain.com
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain haproxy.mydomain.com
http-01 challenge for haproxy.mydomain.com
Cleaning up challenges
Some challenges have failed.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by ragaimeena** [comment]
I have the same issue. The container becomes nonfunctional then. No one is answering this question, it has been posted so many times in different forums/threads.

**Comment by patricklind** [comment]
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.4.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 16, in <module>
    from certbot import crypto_util
  File "/usr/lib/python3.8/site-packages/certbot/crypto_util.py", line 30, in <module>
    from certbot import util
  File "/usr/lib/python3.8/site-packages/certbot/util.py", line 23, in <module>
    from certbot._internal import constants
  File "/usr/lib/python3.8/site-packages/certbot/_internal/constants.py", line 6, in <module>
    from acme import challenges
  File "/usr/lib/python3.8/site-packages/acme/challenges.py", line 11, in <module>
    import requests
  File "/usr/lib/python3.8/site-packages/requests/__init__.py", line 113, in <module>
    from . import packages
  File "/usr/lib/python3.8/site-packages/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
  File "/usr/lib/python3.8/site-packages/idna/__init__.py", line 2, in <module>
    from .core import *
  File "/usr/lib/python3.8/site-packages/idna/core.py", line 1, in <module>
    from . import idnadata
ImportError: cannot import name 'idnadata' from partially initialized module 'idna' (most likely due to a circular import) (/usr/lib/python3.8/site-packages/idna/__init__.py)

**Comment by jessyxavier** [comment]
@Jamyz @ragaimeena I ran in the same problem and I ended up creating a SSL wildcard certificate and works out fine. Just follow the instructions here  at time 4:35 https://www.youtube.com/watch?v=TBGOJA27m_0&t=343s 
I hope this helps
